### ISSUE TITLE
Current Project Files Being Deleted

### ISSUE THREAD

**Issue by yshagit31** [Teamial/DevTrack#7]
I downloaded the extension and while installing it all the files of my project got deleted. I tried it again and same happened. As you can see these files were there earlier but aren't there now.

![Screenshot (1176)](https://github.com/user-attachments/assets/9de1cb8d-b52d-4d4d-8d8e-fbbb76e21e42)

**Comment by Teamial** [comment]
Hey I'm glad you were able to resolve the issue! What fixed it?

**Comment by yshagit31** [comment]
Can you explain me how to use this extension? I just have to download and authenticate it from GitHub. Do I need to create any repo on my github account as well for this to work?

**Comment by Teamial** [comment]
You just download it and authenticate it from GitHub.
You don’t have to create any repository for it to work. Once you
authenticate it to your GitHub account it creates a repo for you and it
will save automatically to that repository.

**Comment by yshagit31** [comment]
When I install it in the working directory of any current project opened in VS Code, all the files in that project are deleted

**Comment by Teamial** [comment]
May I ask what version of dev track do you have installed when you look in
the extensions? Also do you have any uncommitted changes in your working
directory and what operating system are you using? Is it windows because windows has some trouble working with git.

**Comment by yshagit31** [comment]
Version 4.1.11. I had not initialized any repo for that project. Yes, I was working on windows.

**Comment by Teamial** [comment]
Thank you for reporting this critical issue. I've identified and fixed the problem in version 4.1.12 which will be released shortly.

The issue occurred because DevTrack was using aggressive Git cleanup commands during repository initialization without properly checking for existing project files. This could cause untracked files to be removed in projects that weren't already Git repositories.

Changes in 4.1.12:
- Added safety checks for existing project files
- Implemented automatic project backup before Git operations
- Removed aggressive cleanup commands
- Added safer repository initialization for non-Git projects

For extra safety, I recommend:
1. Always initializing a Git repository for your projects before using DevTrack
2. Having a backup of important projects before trying new extensions
3. Using version control as a general best practice

Please update to version 4.1.12 when it's available. The new version will safely preserve your project files while setting up tracking.

Let me know if you experience any other issues. I appreciate you bringing this to my attention - it helps me make DevTrack safer for all users.
